### ISSUE TITLE
Latest update seems to have broken meters

### ISSUE THREAD

**Issue by Panda88CO** [jrester/tesla_powerwall#32]
I had in my code 
 self.meters = self.TPWlocal.get_meters()
 solarPwr = self.meters.solar.instant_power

I get 'MetersAggregates' object has no attribute 'solar'

How to fix it ?

**Comment by ewosborne** [comment]
I ran into the same thing.  My use case is that I'm downloading all the meter data, reshaping it, and uploading it elsewhere.  Before this change I just did:


```
m = pw.get_meters()
metric_data = {
    'solar': [
        ('battery_charge_pct', round(pw.get_charge(), 1)),
        ('battery.imported', m.battery.energy_imported),
        ('battery.exported', m.battery.energy_exported),
```

To get around this change I just added them back in:

```
m = pw.get_meters()
m.battery = m.get_meter(MeterType.BATTERY)
m.load = m.get_meter(MeterType.LOAD)
m.site = m.get_meter(MeterType.SITE)
m.solar = m.get_meter(MeterType.SOLAR)
```

It's a hack, but it works.

**Comment by jrester** [comment]
Ok, those changes seem to result in more confusion than helping anybody. As such I will revert the changes in `0.3.14`, so meters can be accessed using the old method: `meters.solar.instant_power` as well as using .
