### ISSUE TITLE
offgrid

### ISSUE THREAD

**Issue by mihailvovk** [jrester/tesla_powerwall#43]
Hey, I'm trying to go ongrid/offgrid and it is giving me error:

GridStatus.ISLANDED
Traceback (most recent call last):
  File "/root/tesla_powerwall/examples/example.py", line 70, in <module>
    print(power_wall.set_island_mode(IslandMode.OFFGRID))
NameError: name 'IslandMode' is not defined
root@debian:~/tesla_powerwall# 

calling with print(power_wall.set_island_mode(IslandMode.OFFGRID))

git cloned the latest one and installed with build/install

**Comment by jrester** [comment]
Hey @mihailvovk, you probably forgot to append the `IslandMode` to the import in the second line of `example.py`. You could try changing that line to `from tesla_powerwall import Powerwall, Meter, IslandMode`. Hope that helps
