### ISSUE TITLE
Loggout is giving "Powerwall api Error: while decoding json reponse:"

### ISSUE THREAD

**Issue by greyghoster** [jrester/tesla_powerwall#50]
As stated in the title, logout() is throwing an error. The login works and a number of commands execute fine but logout is not clean.

Code:
# Logout
try:
    powerwall.logout()
    print('Logout')
except Exception as err:
    print('Logged out ', err)

Msg returned:
Logged out  Powerwall api error: Error while decoding json of response:

**Comment by jrester** [comment]
Thanks for reporting this bug. I fixed it and it will be release soon together with #48 .
